name: Java ZAP Scan

on:
  push:
    branches:
      - CodeQL-Analysis

jobs:
  codeql:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: 'java,swift,kotlin'

      - name: Build
        run: |
          echo "Building the project"

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven (with Debugging)
        run: mvn clean install -P production -X

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-${{ github.run_id }}  # Ensure the artifact name is unique
          path: target/*.war
