name: Java ZAP Scan

on:
  push:
    branches:
      - CodeQL-Analysis  # Trigger on push to the master branch

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Snyk Scan
        uses: snyk/actions@v1
        with:
          command: test
          args: '--all-projects'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the build environment Available Runners: Explain options like ubuntu-latest, windows-latest, macos-latest
    strategy:
      matrix:
        java-version: [8, 11, 17,21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest version of actions

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'  # Specify Java distribution (AdoptOpenJDK/Temurin)

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven (with Debugging)
        run: mvn clean install -P production -X  #  Enable Maven's debug output (-X)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # Use the latest version
        with:
          name: maven-build
          path: target/*.jar  # Path to the JAR file in the target/ folder
